services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: taskflowdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./api
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/taskflowdb
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
